const base = '/assets/homeguru';

export const homeGuruAssets = {
  appLogo: `${base}/small_logo.png`,
  loginLogo: `${base}/login_biaoti.png`,
  homeText: `${base}/ic_home_text.png`,
  launchBg: `${base}/bj.png`,
  magicWand: `${base}/magic_wand_ic.png`,
  objectDetecting: `${base}/object_detecting.webp`,
  vipCardBg: `${base}/vip_card_bg.png`,
  vipFontLogo: `${base}/vip_font_logo.png`,
  vipSmallIcon: `${base}/vip_small_icon.png`,
  threeDayFree: `${base}/3-day-free.png`,
  splashReplaceBg: `${base}/ha_bg_splash_replace.png`,
  splashReplace: `${base}/ha_splash_replace.png`,
  splashColoringBg: `${base}/ha_bg_splash_coloring.png`,
  splashColoring: `${base}/ha_splash_coloring.png`,
  splashAdd: `${base}/ha_ic_splach_add.png`,
  upload: `${base}/ha_ic_upload.png`,
  paint: `${base}/ha_ic_paint.png`,
  color: `${base}/ha_ic_color.png`,
  texture: `${base}/ha_ic_texture.png`,
  noObject: `${base}/ha_ic_no_object.png`,
  undo: `${base}/ha_ic_undo.png`,
  redo: `${base}/ha_ic_redo.png`,
  defaultColor: `${base}/ha_default_color.png`,
  back: `${base}/ha_ic_back.png`,
  close: `${base}/ha_ic_close.png`,
  discoverScreen: `${base}/screen.png`,
  guide: {
    interiorGood: `${base}/interior_guide_good.png`,
    interiorBad: `${base}/interior_guide_bad.png`,
    exteriorGood: `${base}/exterior_guide_good.png`,
    exteriorBad: `${base}/exterior_guide_bad.png`,
    gardenGood: `${base}/garden_guide_good.png`,
    gardenBad: `${base}/garden_guide_bad.png`,
    floorPlanGood: `${base}/floor_plan_guide_good.png`,
    floorPlanBad: `${base}/floor_plan_guide_bad.png`,
    renovationGood: `${base}/renovation_guide_good.png`,
    renovationBad: `${base}/renovation_guide_bad.png`,
  },
  tabs: {
    home: [`${base}/ha_ic_home_normal.png`, `${base}/ha_ic_home_selected.png`],
    design: [`${base}/ha_ic_design_normal.png`, `${base}/ha_ic_design_selected.png`],
    discover: [`${base}/ha_ic_discover_normal.png`, `${base}/ha_ic_discover_selected.png`],
    mine: [`${base}/ha_ic_profile_normal.png`, `${base}/ha_ic_profile_selected.png`],
  },
};
