import { homeAiAssets } from './assets';
import type { HomeAiSnapshot } from './types';

export const appShellSnapshot: HomeAiSnapshot = {
  features: [
    {
      code: 'floor_plan',
      title: '户型图渲染',
      subtitle: '智能识别布局，一键生成效果图',
      route: 'http://homeai.nav.wanmeixiangsu.com/template_list?featureCode=floor_plan',
      accent: '#fff500',
      guideImage: homeAiAssets.guide.floorPlanGood,
      badImage: homeAiAssets.guide.floorPlanBad,
      icon: homeAiAssets.upload,
    },
    {
      code: 'interior',
      title: '室内设计',
      subtitle: 'AI智能设计，探索千万种装修风格',
      route: 'http://homeai.nav.wanmeixiangsu.com/default?featureCode=interior',
      accent: '#fff500',
      guideImage: homeAiAssets.guide.interiorGood,
      badImage: homeAiAssets.guide.interiorBad,
      icon: homeAiAssets.magicWand,
    },
    {
      code: 'renovation',
      title: '旧房翻新',
      subtitle: '保留空间结构，快速预览翻新后的家。',
      route: 'http://homeai.nav.wanmeixiangsu.com/func_splash?featureCode=renovation',
      accent: '#fff500',
      guideImage: homeAiAssets.guide.renovationGood,
      badImage: homeAiAssets.guide.renovationBad,
      icon: homeAiAssets.paint,
    },
    {
      code: 'garden',
      title: '庭院设计',
      subtitle: '为露台、花园和入户空间生成景观方案。',
      route: 'http://homeai.nav.wanmeixiangsu.com/single_category?featureCode=garden',
      accent: '#fff500',
      guideImage: homeAiAssets.guide.gardenGood,
      badImage: homeAiAssets.guide.gardenBad,
      icon: homeAiAssets.defaultColor,
    },
  ],
  discover: [
    {
      title: '卧室',
      subtitle: '浅蓝卧室与原木收纳',
      coverUrl: homeAiAssets.guide.interiorGood,
      tag: '卧室',
      buildingType: '室内',
      spaceType: '卧室',
    },
    {
      title: '卧室',
      subtitle: '绿植软装卧室',
      coverUrl: homeAiAssets.guide.renovationGood,
      tag: '卧室',
      buildingType: '室内',
      spaceType: '卧室',
    },
    {
      title: '客厅',
      subtitle: '明亮客厅与自然光',
      coverUrl: homeAiAssets.guide.gardenGood,
      tag: '客厅',
      buildingType: '室内',
      spaceType: '客厅',
    },
    {
      title: '客厅',
      subtitle: '现代简约客厅',
      coverUrl: homeAiAssets.guide.exteriorGood,
      tag: '客厅',
      buildingType: '室内',
      spaceType: '客厅',
    },
    {
      title: '住宅',
      subtitle: '社区住宅外观',
      coverUrl: homeAiAssets.guide.floorPlanGood,
      tag: '住宅',
      buildingType: '外观',
      spaceType: '住宅',
    },
    {
      title: '别墅',
      subtitle: '庭院别墅外观',
      coverUrl: homeAiAssets.guide.gardenBad,
      tag: '别墅',
      buildingType: '外观',
      spaceType: '别墅',
    },
    {
      title: '别墅',
      subtitle: '新中式别墅外观',
      coverUrl: homeAiAssets.guide.exteriorBad,
      tag: '别墅',
      buildingType: '外观',
      spaceType: '别墅',
    },
  ],
  works: [],
  user: {
    nickname: '未登录',
    userId: '-',
    avatar: '',
    vipActive: false,
    diamondCount: 0,
    vipLabel: '未登录',
  },
};
