const base = '/assets/homeai';

export const homeAiAssets = {
  appLogo: `${base}/small_logo.png`,
  loginTitle: `${base}/login_biaoti.png`,
  surveyOwner: `${base}/source_survey_owner.png`,
  surveyDesigner: `${base}/source_survey_designer.png`,
  surveyCurios: `${base}/source_survey_curios.png`,
  magicWand: `${base}/magic_wand_ic.png`,
  objectDetecting: `${base}/object_detecting.webp`,
  vipCardBg: `${base}/vip_card_bg.png`,
  vipFontLogo: `${base}/vip_font_logo.png`,
  upload: `${base}/ha_ic_upload.png`,
  paint: `${base}/ha_ic_paint.png`,
  color: `${base}/ha_ic_color.png`,
  texture: `${base}/ha_ic_texture.png`,
  erase: `${base}/ha_ic_earase.png`,
  defaultColor: `${base}/ha_default_color.png`,
  discoverScreen: `${base}/screen.png`,
  guideVideos: [
    { video: `${base}/guide_1.mp4`, poster: `${base}/guide_1_poster.png`, original: `${base}/guide_origin_1.png` },
    { video: `${base}/guide_2.mp4`, poster: `${base}/guide_2_poster.png`, original: `${base}/guide_origin_2.png` },
    { video: `${base}/guide_3.mp4`, poster: `${base}/guide_3_poster.png`, original: `${base}/guide_origin_3.png` },
    { video: `${base}/guide_4.mp4`, poster: `${base}/guide_4_poster.png`, original: `${base}/guide_origin_4.png` },
  ],
  guide: {
    interiorGood: `${base}/interior_guide_good.png`,
    interiorBad: `${base}/interior_guide_bad.png`,
    exteriorGood: `${base}/exterior_guide_good.png`,
    exteriorBad: `${base}/exterior_guide_bad.png`,
    gardenGood: `${base}/garden_guide_good.png`,
    gardenBad: `${base}/garden_guide_bad.png`,
    floorPlanGood: `${base}/floor_plan_guide_good.png`,
    floorPlanBad: `${base}/floor_plan_guide_bad.png`,
    renovationGood: `${base}/renovation_guide_good.png`,
    renovationBad: `${base}/renovation_guide_bad.png`,
  },
  tabs: {
    home: [`${base}/ha_ic_home_normal.png`, `${base}/ha_ic_home_selected.png`],
    design: [`${base}/ha_ic_design_normal.png`, `${base}/ha_ic_design_selected.png`],
    discover: [`${base}/ha_ic_discover_normal.png`, `${base}/ha_ic_discover_selected.png`],
    mine: [`${base}/ha_ic_profile_normal.png`, `${base}/ha_ic_profile_selected.png`],
  },
};
