import { homeAiAssets } from './assets';
import type { HomeAiSnapshot } from './types';

export const demoSnapshot: HomeAiSnapshot = {
  banners: [homeAiAssets.splashReplaceBg, homeAiAssets.splashColoringBg, homeAiAssets.surveyBg],
  features: [
    {
      code: 'interior',
      title: '室内设计',
      subtitle: '上传房间照片，生成全新软装和布局参考。',
      route: 'http://homeai.nav.wanmeixiangsu.com/default?featureCode=interior',
      accent: '#2f7dff',
      guideImage: homeAiAssets.guide.interiorGood,
      badImage: homeAiAssets.guide.interiorBad,
      icon: homeAiAssets.magicWand,
    },
    {
      code: 'renovation',
      title: '旧房翻新',
      subtitle: '保留空间结构，快速预览翻新后的家。',
      route: 'http://homeai.nav.wanmeixiangsu.com/func_splash?featureCode=renovation',
      accent: '#16b58f',
      guideImage: homeAiAssets.guide.renovationGood,
      badImage: homeAiAssets.guide.renovationBad,
      icon: homeAiAssets.paint,
    },
    {
      code: 'garden',
      title: '庭院设计',
      subtitle: '为露台、花园和入户空间生成景观方案。',
      route: 'http://homeai.nav.wanmeixiangsu.com/single_category?featureCode=garden',
      accent: '#88c93d',
      guideImage: homeAiAssets.guide.gardenGood,
      badImage: homeAiAssets.guide.gardenBad,
      icon: homeAiAssets.defaultColor,
    },
    {
      code: 'floor_plan',
      title: '平面图优化',
      subtitle: '识别户型结构，规划更清晰的空间动线。',
      route: 'http://homeai.nav.wanmeixiangsu.com/template_list?featureCode=floor_plan',
      accent: '#ff9f2f',
      guideImage: homeAiAssets.guide.floorPlanGood,
      badImage: homeAiAssets.guide.floorPlanBad,
      icon: homeAiAssets.upload,
    },
  ],
  discover: [
    {
      title: '奶油风客厅',
      subtitle: '柔和浅色墙面、低饱和家具和隐藏灯带。',
      coverUrl: homeAiAssets.guide.interiorGood,
      tag: '室内',
      buildingType: 'interior',
      spaceType: 'living_room',
    },
    {
      title: '庭院步道改造',
      subtitle: '用绿植、石材与低位照明提升入户仪式感。',
      coverUrl: homeAiAssets.guide.gardenGood,
      tag: '庭院',
      buildingType: 'garden',
      spaceType: 'outdoor',
    },
    {
      title: '旧房焕新案例',
      subtitle: '保持原有格局，替换墙面、地板和灯光气质。',
      coverUrl: homeAiAssets.guide.renovationGood,
      tag: '翻新',
      buildingType: 'renovation',
      spaceType: 'bedroom',
    },
    {
      title: '店铺门头灵感',
      subtitle: '更醒目的招牌、橱窗和夜间照明方案。',
      coverUrl: homeAiAssets.guide.exteriorGood,
      tag: '外立面',
      buildingType: 'exterior',
      spaceType: 'storefront',
    },
  ],
  works: [
    {
      id: 'demo-1',
      title: '现代客厅方案',
      status: '已生成',
      coverUrl: homeAiAssets.guide.interiorGood,
      createdAt: '2026-05-20',
    },
    {
      id: 'demo-2',
      title: '旧房翻新草图',
      status: '排队中',
      coverUrl: homeAiAssets.splashReplace,
      createdAt: '2026-05-20',
    },
  ],
  user: {
    nickname: 'HomeAI 访客',
    userId: 'homeai-demo',
    diamondCount: 12,
    vipLabel: '体验会员',
  },
};
